/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.barbershop;
import java.awt.CardLayout;
/**
 *
 * @author ADVAN
 */
public class DashboardAdmin extends javax.swing.JFrame {
    private CardLayout cardLayout;
private PanelDashboardHomeAdmin panelHome;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardAdmin.class.getName());

    /**
     * Creates new form DashboardAdmin
     */
    public DashboardAdmin() {
        initComponents();
    }
public DashboardAdmin(String namaAdmin) {
    this();
    lblAdmin.setText("<html><br>" + namaAdmin + "</html>");
    setLocationRelativeTo(null);

    cardLayout = new CardLayout();
    panelMain.setLayout(cardLayout);

    panelHome = new PanelDashboardHomeAdmin();
    panelMain.add(panelHome, "dashboard");
    panelMain.add(new PanelPelanggan(), "pelanggan");
    panelMain.add(new PanelPegawai(), "pegawai");
    panelMain.add(new PanelLayanan(), "layanan");
   panelTransaksi = new PanelTransaksi();
panelMain.add(panelTransaksi, "transaksi");

panelMain.add(new PanelLaporan(), "laporan");

    cardLayout.show(panelMain, "dashboard");
}

private PanelTransaksi panelTransaksi;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblAdmin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnMenuDashboard = new javax.swing.JButton();
        btnMenuPelanggan = new javax.swing.JButton();
        btnMenuPegawai = new javax.swing.JButton();
        btnMenuLayanan = new javax.swing.JButton();
        btnMenuTransaksi = new javax.swing.JButton();
        btnMenuLaporan = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        panelMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 30, 30));

        jPanel2.setBackground(new java.awt.Color(212, 175, 55));

        lblAdmin.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblAdmin.setText("ADMIN");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Administrator");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/akun.png"))); // NOI18N

        btnMenuDashboard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenuDashboard.setText("Dashboard");
        btnMenuDashboard.addActionListener(this::btnMenuDashboardActionPerformed);

        btnMenuPelanggan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenuPelanggan.setText("Data Pelanggan");
        btnMenuPelanggan.addActionListener(this::btnMenuPelangganActionPerformed);

        btnMenuPegawai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenuPegawai.setText("Data Pegawai");
        btnMenuPegawai.addActionListener(this::btnMenuPegawaiActionPerformed);

        btnMenuLayanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenuLayanan.setText("Data Layanan");
        btnMenuLayanan.addActionListener(this::btnMenuLayananActionPerformed);

        btnMenuTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenuTransaksi.setText("Transaksi");
        btnMenuTransaksi.addActionListener(this::btnMenuTransaksiActionPerformed);

        btnMenuLaporan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenuLaporan.setText("Laporan");
        btnMenuLaporan.addActionListener(this::btnMenuLaporanActionPerformed);

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMenuDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnMenuPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLogout, btnMenuDashboard, btnMenuLaporan, btnMenuLayanan, btnMenuPegawai, btnMenuPelanggan, btnMenuTransaksi});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblAdmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)))
                .addGap(38, 38, 38)
                .addComponent(btnMenuDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenuPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenuPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenuLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenuTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenuLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 350, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnLogout, btnMenuDashboard, btnMenuLaporan, btnMenuLayanan, btnMenuPegawai, btnMenuPelanggan, btnMenuTransaksi});

        panelMain.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuDashboardActionPerformed
        // TODO add your handling code here:
            panelHome.refreshData();
    cardLayout.show(panelMain, "dashboard");
    }//GEN-LAST:event_btnMenuDashboardActionPerformed

    private void btnMenuPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPegawaiActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelMain, "pegawai");

    }//GEN-LAST:event_btnMenuPegawaiActionPerformed

    private void btnMenuPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPelangganActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelMain, "pelanggan");

    }//GEN-LAST:event_btnMenuPelangganActionPerformed

    private void btnMenuLayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuLayananActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelMain, "layanan");
    }//GEN-LAST:event_btnMenuLayananActionPerformed

    private void btnMenuTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuTransaksiActionPerformed
        // TODO add your handling code here:
cardLayout.show(panelMain, "transaksi");
    }//GEN-LAST:event_btnMenuTransaksiActionPerformed

    private void btnMenuLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuLaporanActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelMain, "laporan");
    }//GEN-LAST:event_btnMenuLaporanActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
            this.dispose();
    new LoginForm().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMenuDashboard;
    private javax.swing.JButton btnMenuLaporan;
    private javax.swing.JButton btnMenuLayanan;
    private javax.swing.JButton btnMenuPegawai;
    private javax.swing.JButton btnMenuPelanggan;
    private javax.swing.JButton btnMenuTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables
}
