/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.barbershop;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ADVAN
 */
public class PanelRiwayat extends javax.swing.JPanel {
private int idPegawai;
private DefaultTableModel model;
    /**
     * Creates new form PanelRiwayat
     */
    public PanelRiwayat() {
        initComponents();
    }
public PanelRiwayat(int idPegawai) {
    this();
    this.idPegawai = idPegawai;
    model = new DefaultTableModel(new Object[]{"No", "ID Transaksi", "Pelanggan", "Layanan", "Tanggal", "Jam", "Status"}, 0) {
        public boolean isCellEditable(int r, int c) { return false; }
    };
    tableData.setModel(model);
    txtDari.setText("2024-01-01");
    txtSampai.setText(java.time.LocalDate.now().toString());
    loadData("");
}

public void loadData(String keyword) {
    model.setRowCount(0);
    String sql = "SELECT t.id_transaksi, p.nama AS pelanggan, "
            + "GROUP_CONCAT(l.nama_layanan SEPARATOR ', ') AS layanan, "
            + "DATE_FORMAT(t.tanggal,'%Y-%m-%d') AS tgl, DATE_FORMAT(t.tanggal,'%H:%i') AS jam, t.status "
            + "FROM transaksi t JOIN pelanggan p ON t.id_pelanggan=p.id_pelanggan "
            + "JOIN transaksi_detail d ON d.id_transaksi=t.id_transaksi "
            + "JOIN layanan l ON l.id_layanan=d.id_layanan "
            + "WHERE t.id_pegawai=? AND DATE(t.tanggal) BETWEEN ? AND ? AND p.nama LIKE ? "
            + "GROUP BY t.id_transaksi ORDER BY t.tanggal DESC";
    try (Connection conn = Koneksi.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {
        ps.setInt(1, idPegawai);
        ps.setString(2, txtDari.getText().trim());
        ps.setString(3, txtSampai.getText().trim());
        ps.setString(4, "%" + keyword + "%");
        ResultSet rs = ps.executeQuery();
        int no = 1;
        while (rs.next()) {
            model.addRow(new Object[]{no++, rs.getInt("id_transaksi"), rs.getString("pelanggan"),
                    rs.getString("layanan"), rs.getString("tgl"), rs.getString("jam"), rs.getString("status")});
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat riwayat: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();
        txtDari = new javax.swing.JTextField();
        txtSampai = new javax.swing.JTextField();
        btnCetak = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(46, 46, 46));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RIWAYAT TRANSAKSI");

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "ID Transaksi", "Pelanggan", "Layanan", "Tanggal", "Jam", "Status"
            }
        ));
        jScrollPane1.setViewportView(tableData);

        txtCari.setText("Cari Riwayat...");
        txtCari.addActionListener(this::txtCariActionPerformed);

        txtDari.setText("Dari Tanggal (yyy-mm-dd)");

        txtSampai.setText("Sampai Tanggal (yyy-mm-dd)");

        btnCetak.setBackground(new java.awt.Color(212, 175, 55));
        btnCetak.setText("Cetak Riwayat");
        btnCetak.addActionListener(this::btnCetakActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1048, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSampai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCetak, txtCari, txtDari, txtSampai});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnCetak, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDari, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSampai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCetak, txtCari, txtDari, txtSampai});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
            try {
        tableData.print();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal cetak: " + e.getMessage());
    }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
        loadData(txtCari.getText().trim());
    }//GEN-LAST:event_txtCariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableData;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtDari;
    private javax.swing.JTextField txtSampai;
    // End of variables declaration//GEN-END:variables
}
