/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.barbershop;
import java.sql.*;
import java.math.BigDecimal;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ADVAN
 */
public class PanelDashboardHomeAdmin extends javax.swing.JPanel {
private DefaultTableModel model;
    /**
     * Creates new form PanelDashboardHomeAdmin
     */
    public PanelDashboardHomeAdmin() {
        initComponents();
        model = new DefaultTableModel(new Object[]{"No", "No.Transaksi", "Pelanggan", "Layanan", "Total", "Tanggal"}, 0) {
    public boolean isCellEditable(int r, int c) { return false; }
};
tableTerbaru.setModel(model);
refreshData();
    }
public void refreshData() {
    try (Connection conn = Koneksi.getConnection()) {
        if (conn == null) return;
        try (Statement st = conn.createStatement()) {
            ResultSet rs = st.executeQuery("SELECT COUNT(*) FROM pelanggan");
            if (rs.next()) lblTotalPelanggan.setText(String.valueOf(rs.getInt(1)));

            rs = st.executeQuery("SELECT COUNT(*) FROM pegawai");
            if (rs.next()) lblTotalPegawai.setText(String.valueOf(rs.getInt(1)));

            rs = st.executeQuery("SELECT COUNT(*) FROM transaksi");
            if (rs.next()) lblTotalTransaksi.setText(String.valueOf(rs.getInt(1)));

            rs = st.executeQuery("SELECT IFNULL(SUM(total),0) FROM transaksi");
if (rs.next()) {
    java.text.DecimalFormat df = new java.text.DecimalFormat("#,###");
    lblTotalPendapatan.setText("Rp " + df.format(rs.getBigDecimal(1)));}
        }

        model.setRowCount(0);
        String sql = "SELECT t.id_transaksi, p.nama AS pelanggan, "
                + "GROUP_CONCAT(l.nama_layanan SEPARATOR ', ') AS layanan, t.total, t.tanggal "
                + "FROM transaksi t "
                + "JOIN pelanggan p ON t.id_pelanggan=p.id_pelanggan "
                + "JOIN transaksi_detail d ON d.id_transaksi=t.id_transaksi "
                + "JOIN layanan l ON l.id_layanan=d.id_layanan "
                + "GROUP BY t.id_transaksi ORDER BY t.tanggal DESC LIMIT 10";
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ResultSet rs = ps.executeQuery();
            int no = 1;
            while (rs.next()) {
                java.text.DecimalFormat df = new java.text.DecimalFormat("#,###");

java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd-MM-yyyy HH:mm:ss");

String tanggal = sdf.format(rs.getTimestamp("tanggal"));

model.addRow(new Object[]{
    no++,
    rs.getInt("id_transaksi"),
    rs.getString("pelanggan"),
    rs.getString("layanan"),
    df.format(rs.getBigDecimal("total")),
    tanggal
});
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTotalPelanggan = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblJudulPelanggan = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblTotalPegawai = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblJudulPegawai = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblTotalTransaksi = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblJudulTransaksi = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblTotalPendapatan = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblJudulPendapatan = new javax.swing.JLabel();
        lblJudulTabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTerbaru = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(46, 46, 46));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DASHBOARD ADMIN");

        lblTotalPelanggan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalPelanggan.setText("0");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Total Pelanggan");

        lblJudulPelanggan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblJudulPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/team.png"))); // NOI18N
        lblJudulPelanggan.setText("Pelanggan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(lblTotalPelanggan))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblJudulPelanggan)
                            .addComponent(jLabel6))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudulPelanggan)
                .addGap(34, 34, 34)
                .addComponent(lblTotalPelanggan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        lblTotalPegawai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalPegawai.setText("0");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Total Pegawai");

        lblJudulPegawai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblJudulPegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/pegawai.png"))); // NOI18N
        lblJudulPegawai.setText("Pegawai");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblJudulPegawai)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(84, 84, 84)
                            .addComponent(lblTotalPegawai))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(jLabel7))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudulPegawai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalPegawai)
                .addGap(36, 36, 36)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        lblTotalTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalTransaksi.setText("0");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Total Transaksi");

        lblJudulTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblJudulTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/transaksi.png"))); // NOI18N
        lblJudulTransaksi.setText("Transaksi");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblJudulTransaksi)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(87, 87, 87)
                            .addComponent(lblTotalTransaksi))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(jLabel8))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudulTransaksi)
                .addGap(36, 36, 36)
                .addComponent(lblTotalTransaksi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        lblTotalPendapatan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalPendapatan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalPendapatan.setText("0");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Total Pendapatan");

        lblJudulPendapatan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblJudulPendapatan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudulPendapatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/money.png"))); // NOI18N
        lblJudulPendapatan.setText("Pendapatan");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTotalPendapatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(lblJudulPendapatan)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(39, 39, 39))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudulPendapatan)
                .addGap(36, 36, 36)
                .addComponent(lblTotalPendapatan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        lblJudulTabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJudulTabel.setForeground(new java.awt.Color(255, 255, 255));
        lblJudulTabel.setText("Transaksi Terbaru");

        tableTerbaru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No. Transaksi", "Pelanggan", "Layanan", "Total", "Tanggal"
            }
        ));
        jScrollPane1.setViewportView(tableTerbaru);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblJudulTabel))
                        .addGap(0, 907, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel2, jPanel4, jPanel5, jPanel6});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(lblJudulTabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJudulPegawai;
    private javax.swing.JLabel lblJudulPelanggan;
    private javax.swing.JLabel lblJudulPendapatan;
    private javax.swing.JLabel lblJudulTabel;
    private javax.swing.JLabel lblJudulTransaksi;
    private javax.swing.JLabel lblTotalPegawai;
    private javax.swing.JLabel lblTotalPelanggan;
    private javax.swing.JLabel lblTotalPendapatan;
    private javax.swing.JLabel lblTotalTransaksi;
    private javax.swing.JTable tableTerbaru;
    // End of variables declaration//GEN-END:variables
}
