/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.barbershop;
import java.sql.*;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.DecimalFormat;

/**
 *
 * @author ADVAN
 */

public class PanelTransaksi extends javax.swing.JPanel {
    
private DefaultTableModel modelDetail;
private final List<Integer> idLayananList = new ArrayList<>();
private final List<BigDecimal> hargaList = new ArrayList<>();

static class ComboItem {
    int id; String label; BigDecimal harga;
    ComboItem(int id, String label) { this.id = id; this.label = label; }
    ComboItem(int id, String label, BigDecimal harga) { this.id = id; this.label = label; this.harga = harga; }
    public String toString() { return label; }
}
    /**
     * Creates new form PanelTransaksi
     */
    public PanelTransaksi() {
        initComponents();
        modelDetail = new DefaultTableModel(new Object[]{"No", "Layanan", "Harga", "Aksi"}, 0) {
    public boolean isCellEditable(int r, int c) { return false; }
};
tableDetail.setModel(modelDetail);
tableDetail.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {

        int row = tableDetail.rowAtPoint(evt.getPoint());
        int col = tableDetail.columnAtPoint(evt.getPoint());

        // Kolom Aksi (index 3)
        if (col == 3) {

            int konfirmasi = JOptionPane.showConfirmDialog(
                    null,
                    "Hapus layanan ini?",
                    "Konfirmasi",
                    JOptionPane.YES_NO_OPTION);

            if (konfirmasi == JOptionPane.YES_OPTION) {

                idLayananList.remove(row);
                hargaList.remove(row);
                modelDetail.removeRow(row);

                // Perbaiki nomor
                for (int i = 0; i < modelDetail.getRowCount(); i++) {
                    modelDetail.setValueAt(i + 1, i, 0);
                }

                hitungTotal();
            }
        }
    }
});

txtTanggal.setText(java.time.LocalDate.now().toString());
txtTanggal.setEditable(false);
txtNoTransaksi.setEditable(false);

loadCombo();

cbLayanan.addActionListener(e -> {
    ComboItem item = (ComboItem) cbLayanan.getSelectedItem();
    if (item != null) {
        DecimalFormat df = new DecimalFormat("#,###");
        txtHarga.setText(df.format(item.harga));
    }
});

if (cbLayanan.getItemCount() > 0) {
    cbLayanan.setSelectedIndex(0);
}
        
    }
    
public void loadCombo() {
    cbPelanggan.removeAllItems();
    cbPegawai.removeAllItems();
    cbLayanan.removeAllItems();
    try (Connection conn = Koneksi.getConnection()) {
        if (conn == null) return;
        try (Statement st = conn.createStatement(); ResultSet rs = st.executeQuery("SELECT id_pelanggan, nama FROM pelanggan")) {
            while (rs.next()) ((javax.swing.JComboBox) cbPelanggan).addItem(new ComboItem(rs.getInt(1), rs.getString(2)));
        }
        try (Statement st = conn.createStatement(); ResultSet rs = st.executeQuery("SELECT id_pegawai, nama FROM pegawai WHERE role = 'Pegawai'")) {
    while (rs.next()) ((javax.swing.JComboBox) cbPegawai).addItem(new ComboItem(rs.getInt(1), rs.getString(2)));
}
        try (Statement st = conn.createStatement(); ResultSet rs = st.executeQuery("SELECT id_layanan, nama_layanan, harga FROM layanan")) {
            while (rs.next()) ((javax.swing.JComboBox) cbLayanan).addItem(
    new ComboItem(
        rs.getInt(1),
        rs.getString(2),
        rs.getBigDecimal(3)
    )
);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal load data: " + e.getMessage());
    }
    
}

private void hitungTotal() {
    BigDecimal total = BigDecimal.ZERO;
    for (BigDecimal h : hargaList)
        total = total.add(h);

    DecimalFormat df = new DecimalFormat("#,###");
    lblTotal.setText("Total: Rp " + df.format(total));
}

private void resetForm() {
    idLayananList.clear();
    hargaList.clear();
    modelDetail.setRowCount(0);
    lblTotal.setText("Total: Rp 0");
    txtNoTransaksi.setText("");
    txtHarga.setText("");
    
    loadCombo();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDetail = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNoTransaksi = new javax.swing.JTextField();
        txtTanggal = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnBayar = new javax.swing.JButton();
        cbPelanggan = new javax.swing.JComboBox<>();
        cbPegawai = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbLayanan = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(46, 46, 46));

        tableDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Tanggal", "No. Transaksi", "Pelanggan", "Total"
            }
        ));
        jScrollPane1.setViewportView(tableDetail);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TRANSAKSI");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No. Transaksi");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tanggal");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pelanggan");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pegawai");

        btnTambah.setBackground(new java.awt.Color(25, 135, 84));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(this::btnTambahActionPerformed);

        btnReset.setBackground(new java.awt.Color(73, 80, 87));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnBayar.setBackground(new java.awt.Color(54, 109, 213));
        btnBayar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBayar.setForeground(new java.awt.Color(255, 255, 255));
        btnBayar.setText("Bayar");
        btnBayar.addActionListener(this::btnBayarActionPerformed);

        cbPelanggan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbPegawai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Layanan");

        cbLayanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Harga");

        jPanel2.setBackground(new java.awt.Color(212, 175, 55));

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotal.setText("Total: Rp 0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotal)
                .addContainerGap(707, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(lblTotal)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(txtNoTransaksi)
                            .addComponent(txtTanggal)
                            .addComponent(cbLayanan, javax.swing.GroupLayout.Alignment.TRAILING, 0, 262, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(cbPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(cbPelanggan, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbLayanan, cbPegawai, cbPelanggan});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNoTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtNoTransaksi, txtTanggal});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbLayanan, cbPegawai, cbPelanggan});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
            ComboItem item = (ComboItem) cbLayanan.getSelectedItem();
    if (item == null) {
        JOptionPane.showMessageDialog(this, "Pilih layanan dulu.");
        return;
    }
    idLayananList.add(item.id);
    hargaList.add(item.harga);
    DecimalFormat df = new DecimalFormat("#,###");

modelDetail.addRow(new Object[]{
    modelDetail.getRowCount() + 1,
    item.label,
    df.format(item.harga),
    "Hapus"
});
    hitungTotal();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
            ComboItem pelanggan = (ComboItem) cbPelanggan.getSelectedItem();
    ComboItem pegawai = (ComboItem) cbPegawai.getSelectedItem();

    if (cbPelanggan.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "Pilih pelanggan dulu!");
        return;
    }
    if (cbPegawai.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "Pilih pegawai dulu!");
        return;
    }
    if (idLayananList.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Tambahkan minimal 1 layanan dulu!");
        return;
    }

    BigDecimal total = BigDecimal.ZERO;
    for (BigDecimal h : hargaList) total = total.add(h);

    try (Connection conn = Koneksi.getConnection()) {
        conn.setAutoCommit(false);
        int idTransaksi;
        try (PreparedStatement ps = conn.prepareStatement(
                "INSERT INTO transaksi (id_pelanggan, id_pegawai, total, status) VALUES (?,?,?,?)",
                Statement.RETURN_GENERATED_KEYS)) {
            ps.setInt(1, pelanggan.id);
            ps.setInt(2, pegawai.id);
            ps.setBigDecimal(3, total);
            ps.setString(4, "Menunggu");
            ps.executeUpdate();
            ResultSet keys = ps.getGeneratedKeys();
            keys.next();
            idTransaksi = keys.getInt(1);
        }
        try (PreparedStatement ps = conn.prepareStatement(
                "INSERT INTO transaksi_detail (id_transaksi, id_layanan, harga) VALUES (?,?,?)")) {
            for (int i = 0; i < idLayananList.size(); i++) {
                ps.setInt(1, idTransaksi);
                ps.setInt(2, idLayananList.get(i));
                ps.setBigDecimal(3, hargaList.get(i));
                ps.addBatch();
            }
            ps.executeBatch();
        }
        conn.commit();
        txtNoTransaksi.setText(String.valueOf(idTransaksi));
        JOptionPane.showMessageDialog(this, "Transaksi berhasil disimpan! No: " + idTransaksi);
        resetForm();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal simpan transaksi: " + e.getMessage());
    }
    }//GEN-LAST:event_btnBayarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cbLayanan;
    private javax.swing.JComboBox<String> cbPegawai;
    private javax.swing.JComboBox<String> cbPelanggan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tableDetail;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtNoTransaksi;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
