/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.barbershop;
import java.sql.*;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
/**
 *
 * @author ADVAN
 */
public class PanelLaporan extends javax.swing.JPanel {
    private DefaultTableModel model;

    /**
     * Creates new form PanelLaporan
     */
    public PanelLaporan() {
        initComponents();
        model = new DefaultTableModel(new Object[]{"No", "Tanggal", "No. Transaksi", "Pelanggan", "Total"}, 0) {
    public boolean isCellEditable(int r, int c) { return false; }
};
tableData.setModel(model);


txtDari.setText("2024-01-01");
txtSampai.setText(java.time.LocalDate.now().toString());

tampilkanLaporan();
    }
private void tampilkanLaporan() {
    model.setRowCount(0);
    String jenis = (String) cbJenisLaporan.getSelectedItem();
    BigDecimal total = BigDecimal.ZERO;
    
    DecimalFormat df = new DecimalFormat("#,###");
SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy HH:mm");

    try (Connection conn = Koneksi.getConnection()) {
        if ("Laporan Data Pelanggan".equals(jenis)) {
            String sql = "SELECT nama, no_hp, alamat FROM pelanggan ORDER BY nama";
            try (Statement st = conn.createStatement(); ResultSet rs = st.executeQuery(sql)) {
                int no = 1;
                while (rs.next()) {
                    model.addRow(new Object[]{no++, rs.getString("nama"), rs.getString("no_hp"), rs.getString("alamat"), ""});
                }
            }
            lblTotal.setText("Total Pelanggan: " + (model.getRowCount()));
            return;
        }

        String sql;
        if ("Laporan Transaksi Bulanan".equals(jenis)) {
            sql = "SELECT t.id_transaksi, t.tanggal, p.nama AS pelanggan, t.total FROM transaksi t "
                + "JOIN pelanggan p ON t.id_pelanggan=p.id_pelanggan "
                + "WHERE DATE_FORMAT(t.tanggal,'%Y-%m') = DATE_FORMAT(?, '%Y-%m') ORDER BY t.tanggal DESC";
        } else {
            // Harian & Pendapatan pakai rentang tanggal dari/sampai
            sql = "SELECT t.id_transaksi, t.tanggal, p.nama AS pelanggan, t.total FROM transaksi t "
                + "JOIN pelanggan p ON t.id_pelanggan=p.id_pelanggan "
                + "WHERE DATE(t.tanggal) BETWEEN ? AND ? ORDER BY t.tanggal DESC";
        }

        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            if ("Laporan Transaksi Bulanan".equals(jenis)) {
                ps.setString(1, txtDari.getText().trim());
            } else {
                ps.setString(1, txtDari.getText().trim());
                ps.setString(2, txtSampai.getText().trim());
            }
            ResultSet rs = ps.executeQuery();
            int no = 1;
            while (rs.next()) {
                BigDecimal t = rs.getBigDecimal("total");
                total = total.add(t);
                model.addRow(new Object[]{
    no++,
    sdf.format(rs.getTimestamp("tanggal")),
    rs.getInt("id_transaksi"),
    rs.getString("pelanggan"),
    df.format(t)
});
            }
        }
       lblTotal.setText("Total: Rp " + df.format(total));
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat laporan: " + e.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDari = new javax.swing.JTextField();
        btnTampilkan = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        cbJenisLaporan = new javax.swing.JComboBox<>();
        txtSampai = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(46, 46, 46));

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Tanggal", "No. Transaksi", "Pelanggan", "Total"
            }
        ));
        jScrollPane1.setViewportView(tableData);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LAPORAN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jenis Laporan");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Dari Tanggal");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sampai Tanggal");

        btnTampilkan.setBackground(new java.awt.Color(25, 135, 84));
        btnTampilkan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTampilkan.setForeground(new java.awt.Color(255, 255, 255));
        btnTampilkan.setText("Tampilkan");
        btnTampilkan.addActionListener(this::btnTampilkanActionPerformed);

        btnCetak.setBackground(new java.awt.Color(54, 109, 213));
        btnCetak.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCetak.setForeground(new java.awt.Color(255, 255, 255));
        btnCetak.setText("Cetak PDF");
        btnCetak.addActionListener(this::btnCetakActionPerformed);

        jPanel2.setBackground(new java.awt.Color(212, 175, 55));

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotal.setText("Total: Rp 0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(lblTotal)
                .addContainerGap())
        );

        cbJenisLaporan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laporan Transaksi Harian", "Laporan Transaksi Bulanan", "Laporan Pendapatan", "Laporan Data Pelanggan" }));
        cbJenisLaporan.addItemListener(this::cbJenisLaporanItemStateChanged);
        cbJenisLaporan.addActionListener(this::cbJenisLaporanActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(txtDari)
                            .addComponent(jLabel4)
                            .addComponent(btnTampilkan, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(btnCetak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbJenisLaporan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSampai))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbJenisLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDari, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSampai, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnTampilkan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilkanActionPerformed
        // TODO add your handling code here:
        tampilkanLaporan();
    }//GEN-LAST:event_btnTampilkanActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
            try {
        tableData.print();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal cetak: " + e.getMessage());
    }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void cbJenisLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisLaporanActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbJenisLaporanActionPerformed

    private void cbJenisLaporanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbJenisLaporanItemStateChanged
        // TODO add your handling code here:
         if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
        tampilkanLaporan();
    }
    }//GEN-LAST:event_cbJenisLaporanItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnTampilkan;
    private javax.swing.JComboBox<String> cbJenisLaporan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tableData;
    private javax.swing.JTextField txtDari;
    private javax.swing.JTextField txtSampai;
    // End of variables declaration//GEN-END:variables
}
