package com.barbershop;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author ADVAN
 */
public class PanelDashboardHomePegawai extends javax.swing.JPanel {
private int idPegawai;
private DefaultTableModel model;
    /**
     * Creates new form PanelDashboardHomePegawai
     */
    public PanelDashboardHomePegawai() {
        initComponents();
        
    }
public PanelDashboardHomePegawai(int idPegawai) {
    this();
    this.idPegawai = idPegawai;
    model = new DefaultTableModel(new Object[]{"No", "Jam", "Pelanggan", "Layanan", "Status"}, 0) {
        public boolean isCellEditable(int r, int c) { return false; }
    };
    tableJadwalMini.setModel(model);
    refreshData();
}
public void refreshData() {
    String sqlStat = "SELECT COUNT(DISTINCT id_pelanggan) AS jml_pelanggan, COUNT(*) AS jml_transaksi, "
            + "IFNULL(SUM(total),0) AS pendapatan FROM transaksi WHERE id_pegawai=? AND DATE(tanggal)=CURDATE()";
    try (Connection conn = Koneksi.getConnection(); PreparedStatement ps = conn.prepareStatement(sqlStat)) {
        ps.setInt(1, idPegawai);
        ResultSet rs = ps.executeQuery();
        if (rs.next()) {
            lblPelangganHariIni.setText(String.valueOf(rs.getInt("jml_pelanggan")));
            lblTransaksiHariIni.setText(String.valueOf(rs.getInt("jml_transaksi")));
            lblPendapatanHariIni.setText("Rp " + rs.getBigDecimal("pendapatan"));
        }
    } catch (Exception e) { e.printStackTrace(); }

    model.setRowCount(0);
    String sql = "SELECT t.id_transaksi, DATE_FORMAT(t.tanggal,'%H:%i') AS jam, p.nama AS pelanggan, "
            + "GROUP_CONCAT(l.nama_layanan SEPARATOR ', ') AS layanan, t.status "
            + "FROM transaksi t JOIN pelanggan p ON t.id_pelanggan=p.id_pelanggan "
            + "JOIN transaksi_detail d ON d.id_transaksi=t.id_transaksi "
            + "JOIN layanan l ON l.id_layanan=d.id_layanan "
            + "WHERE t.id_pegawai=? AND DATE(t.tanggal)=CURDATE() GROUP BY t.id_transaksi ORDER BY t.tanggal";
    try (Connection conn = Koneksi.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {
        ps.setInt(1, idPegawai);
        ResultSet rs = ps.executeQuery();
        int no = 1;
        while (rs.next()) {
            model.addRow(new Object[]{no++, rs.getString("jam"), rs.getString("pelanggan"), rs.getString("layanan"), rs.getString("status")});
        }
    } catch (Exception e) { e.printStackTrace(); }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblTransaksiHariIni = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblJudulTransaksi = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblPelangganHariIni = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblJudulPelanggan = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblPendapatanHariIni = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblJudulPendapatan = new javax.swing.JLabel();
        lblJudulTabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableJadwalMini = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(46, 46, 46));

        lblTransaksiHariIni.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTransaksiHariIni.setText("0");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Transaksi");

        lblJudulTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblJudulTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/transaksi.png"))); // NOI18N
        lblJudulTransaksi.setText("Transaksi Hari Ini");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(lblTransaksiHariIni))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblJudulTransaksi))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel8)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudulTransaksi)
                .addGap(36, 36, 36)
                .addComponent(lblTransaksiHariIni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DASHBOARD PEGAWAI");

        lblPelangganHariIni.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPelangganHariIni.setText("0");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Orang");

        lblJudulPelanggan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblJudulPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/team.png"))); // NOI18N
        lblJudulPelanggan.setText("Pelanggan Hari Ini");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(lblPelangganHariIni))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblJudulPelanggan))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel6)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudulPelanggan)
                .addGap(34, 34, 34)
                .addComponent(lblPelangganHariIni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        lblPendapatanHariIni.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPendapatanHariIni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPendapatanHariIni.setText("0");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Total Pendapatan");

        lblJudulPendapatan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblJudulPendapatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/money.png"))); // NOI18N
        lblJudulPendapatan.setText("Pendapatan Hari Ini");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel9))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblJudulPendapatan)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addComponent(lblPendapatanHariIni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudulPendapatan)
                .addGap(36, 36, 36)
                .addComponent(lblPendapatanHariIni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        lblJudulTabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJudulTabel.setForeground(new java.awt.Color(255, 255, 255));
        lblJudulTabel.setText("Jadwal Hari Ini");

        tableJadwalMini.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Jam", "Pelanggan", "Layanan", "Status"
            }
        ));
        jScrollPane1.setViewportView(tableJadwalMini);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblJudulTabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel2, jPanel5, jPanel6});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(lblJudulTabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJudulPelanggan;
    private javax.swing.JLabel lblJudulPendapatan;
    private javax.swing.JLabel lblJudulTabel;
    private javax.swing.JLabel lblJudulTransaksi;
    private javax.swing.JLabel lblPelangganHariIni;
    private javax.swing.JLabel lblPendapatanHariIni;
    private javax.swing.JLabel lblTransaksiHariIni;
    private javax.swing.JTable tableJadwalMini;
    // End of variables declaration//GEN-END:variables
}
